### ISSUE TITLE
Lib not loaded libhwloc.5.dylib

### ISSUE THREAD

**Issue by mikeccuk2005** [killswitch-GUI/xmr-stak-osx#4]
```
dyld: Library not loaded: /usr/local/opt/hwloc/lib/libhwloc.5.dylib
  Referenced from: /Users/digithun/xmr-stak-osx/./xmr-stak
  Reason: image not found
```

I already tried 
```
brew install hwloc
```

What I had installed was actually
```
/usr/local/opt/hwloc/lib/libhwloc.
libhwloc.12.dylib  libhwloc.a         libhwloc.dylib
```

Is there a specific version of hwloc I need to install?

**Comment by sandyeggoxj** [comment]
I have the same issue... Any fixes?

**Comment by mikeccuk2005** [comment]
I use docker-compose heres the docker-compose.yaml
It's much easier to setup this way on any machine
```
services:
  miner_1:
    image: masterroshi/monero-miner
    restart: always
    environment:
     - POOL_URL=gulf.moneroocean.stream:10001
     - POOL_USER=mymonero_public_key
     - POOL_PW=name:x
     - MAX_CPU=100
```
